SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddMain](@YouthFName nchar(30)=NULL,
@YouthLName nchar(30)=NULL,
@YouthID nchar(30)=NULL,
@Medicaid bit=NULL,
@CurrentProvider nchar(30)=NULL,
@CurrentProviderPhone nchar(30)=NULL,
@CareGiverFName nchar(30)=NULL,
@CareGiverLName nchar(30)=NULL,
@CareGiverPhone nchar(30)=NULL,
@CareGiverAlternatePhone nchar(30)=NULL,
@CareGiveremail nchar(50)=NULL,
@CareGiverAddress1 nchar(30)=NULL,
@CareGiverAddress2 nchar(30)=NULL,
@CareGiverCity nchar(30)=NULL,
@CareGiverZip nchar(10)=NULL,
@MainCreator nchar(10)=NULL,
@ProgramFK int=NULL,
@CaregiverAgreesToInterview bit=NULL,
@YouthPhone nchar(30)=NULL,
@YouthAlternatePhone nchar(30)=NULL,
@Youthemail nchar(50)=NULL,
@YouthAddress1 nchar(30)=NULL,
@YouthAddress2 nchar(30)=NULL,
@YouthCity nchar(30)=NULL,
@YouthZip nchar(10)=NULL,
@YouthAgreesToInterview bit=NULL)
AS
INSERT INTO Main(
YouthFName,
YouthLName,
YouthID,
Medicaid,
CurrentProvider,
CurrentProviderPhone,
CareGiverFName,
CareGiverLName,
CareGiverPhone,
CareGiverAlternatePhone,
CareGiveremail,
CareGiverAddress1,
CareGiverAddress2,
CareGiverCity,
CareGiverZip,
MainCreator,
ProgramFK,
CaregiverAgreesToInterview,
YouthPhone,
YouthAlternatePhone,
Youthemail,
YouthAddress1,
YouthAddress2,
YouthCity,
YouthZip,
YouthAgreesToInterview
)
VALUES(
@YouthFName,
@YouthLName,
@YouthID,
@Medicaid,
@CurrentProvider,
@CurrentProviderPhone,
@CareGiverFName,
@CareGiverLName,
@CareGiverPhone,
@CareGiverAlternatePhone,
@CareGiveremail,
@CareGiverAddress1,
@CareGiverAddress2,
@CareGiverCity,
@CareGiverZip,
@MainCreator,
@ProgramFK,
@CaregiverAgreesToInterview,
@YouthPhone,
@YouthAlternatePhone,
@Youthemail,
@YouthAddress1,
@YouthAddress2,
@YouthCity,
@YouthZip,
@YouthAgreesToInterview
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
